language: python
services:
  - elasticsearch
sudo: required
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pgmagick libgraphicsmagick++1-dev libboost-python-dev
install:
  - pip install -r requirements.txt 
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=elections manage.py test elections
  - coverage report -m
after_script:
  - coveralls --verbose
